### ISSUE TITLE
Add the .sln files for sample projects

### ISSUE THREAD

**Issue by GFoley83** [tnc1997/samples#24]
Hi there. Love your examples & youtube videos for IdS. 
Could you add the .sln files for the various sample please? 
E.g. When I just want to open and run the `authenticating-a-dotnet-console-application-using-identityserver` for example.

Optionally, if there's a really simple way to accomplish this with Rider, it would be good to call that out.

**Comment by tnc1997** [comment]
Hi @GFoley83, thank you for your positive feedback, I will aim to add a '.sln' file to each of the samples by the end of this week.

**Comment by GFoley83** [comment]
Additional request, there's a couple of other things that make the solution tricky to work with when you initially check it out.

1. The IdS clients that you add in your videos; the code to add those clients isn't checked into the solution so when you run the project you have no clients and no clear instructions to add them. Ideally this could be a seed class like shown here:
https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/WebUI/Program.cs
https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/Infrastructure/Persistence/ApplicationDbContextSeed.cs
2. The `.sln` files as mentioned previously.

Unrelated question: there are various aspects of the multiple sample projects that I personally, would love to see together in an all-in-one "final" type solution that I think the community would really benefit from 
e.g. following the API / Console / SPA / IdS project structure with: 

- .NET Core Identity
- JWT support
- Policy / Roles
- Swagger / OpenAPI 
- Entity Framework Core

Feel free to ignore all of this course. There's a big gap out there of a proper, useable, starter project for the new Duende IdentityServer (most are next to useless hello world type things) and I think if you combine some of your existing sample projects into another repo, you would have exactly that.

Also I really have to commend you on your YouTube videos; your very thorough breakdown & explanation of various parts of the solution e.g. the make up of the docker files and what the various parts mean, should be videos in their own right. You should keep it up!

**Comment by tnc1997** [comment]
Thank you very much for your kind words, I'm glad that you've found the videos helpful. Would you mind opening a separate issue for adding IdentityServer seed logic to the samples? That way I can track the changes independently of each other. Also, if you are happy to open another issue for adding a sample that combines everything together, I'm sure I will be able to take a look!

**Comment by tnc1997** [comment]
Hi @GFoley83, could I get you to checkout [chore/24](https://github.com/tnc1997/samples/tree/chore/24) and test the solution files (and optionally the run configurations)?

**Comment by GFoley83** [comment]
I've tested all the sample solutions and can confirm that they all build fine which is awesome but I'm unable to run them with docker compose currently because of the issue described in #27.

**Comment by tnc1997** [comment]
Cheers for testing the solution files, I'll merge that branch into main, and investigate `docker compose` separately in #27.
