### ISSUE TITLE
Add identity Db seed data to solution 

### ISSUE THREAD

**Issue by GFoley83** [tnc1997/samples#25]
Please add all the required seed data code to the solution e.g. auth clients, so that when you first run the project, the Db will be populated with all the correct data to run the sample. Ideally, the logic would be idempotent also e.g. Add or Update

Example seed structure:
https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/WebUI/Program.cs
https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/Infrastructure/Persistence/ApplicationDbContextSeed.cs

Or what you have here is also fine:
https://github.com/tnc1997/samples/blob/2677309c73284c84d9c3807a9396550d66793b48/authenticating-an-aspnet-core-web-application-using-identityserver/IdentityServer/Program.cs

**Comment by tnc1997** [comment]
Hi @GFoley83, I've just been going over the samples and I think that all of the ones that use Entity Framework contain DB seed data, that being said I might have missed one! Could you confirm which Entity Framework sample(s) are missing seed data?

**Comment by GFoley83** [comment]
I've just looked again; sincere apologies! I think what might have thrown me off was switching between some solutions which had in memory vs. stored in Db? In any case, I'll close this off. Apologies for wasting your time on that one!

**Comment by tnc1997** [comment]
No need to apologise, that is probably what threw you off, some of the samples are in-memory and some use a database 😆
