### ISSUE TITLE
Create a combined sample solution example 

### ISSUE THREAD

**Issue by GFoley83** [tnc1997/samples#26]
If would be great if you could create a solution that combines various functionality of your sample projects into one complete solution. 

This would offer an excellent starter project using Duende IdentityServer that goes beyond the basic "hello world" starter templates that currently exist and instead provide an excellent example of a more real-world solution.

A solution structure in the style of: 

- API - w/ authorization code & refresh token
- Console - w/ client credentials 
- SPA - w/ authorization code & refresh token
- IdentityServer 

seems logical. The functionality from your samples that I think would be particular useful are:

- .NET Core Identity - As we're pretty much always going to want to store user info somewhere
- JWTs
- Policy / Role claims 
- Scopes
- Swagger / OpenAPI w/ security
- Entity Framework Core w/ PostgresSQL
- Docker
- Sample UI - To login/register - https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI.AspNetIdentity

I'm also happy to help with some of this if needed!

**Comment by GFoley83** [comment]
Just wondering if there's any progress with the @tnc1997 or if there's anything I can help with?

**Comment by tnc1997** [comment]
> Just wondering if there's any progress with the @tnc1997 or if there's anything I can help with?

Hi @GFoley83, I am currently in the process of putting a rough plan together for a combined sample.

I am planning to make some meaningful progress on a video and sample this Bank Holiday weekend.

Out of interest, do you think that a video accompanying the sample would be useful in this scenario?

**Comment by GFoley83** [comment]
That sounds really great.
I would say that a supporting video, or indeed anything that provides additional context/explanation, would always be desirable. So to answer your questions, yes, definitely. Or at the very least, given you already have multiple videos that explain some of the more complex concepts, you could provide links to those instead/in the interim.

Separately, I've also been looking various solutions and ideas to support multi-tenancy w/ roles for IdS, via additional claims stored against a user. It's an interesting challenge that doesn't yet have a  uniform or standardised approach. Given what tenant(s) you belong to and your role in that tenant, is very much tied to your identity, it makes sense to me for IdS to support that. I digress.

**Comment by tnc1997** [comment]
Hi @GFoley83, could I get you to try out the sample and let me know if you experience any issues?

**Comment by GFoley83** [comment]
I'll definitely have a bash at it today @tnc1997.

**Comment by GFoley83** [comment]
Hi @tnc1997 I've given the solution and pretty decent testing. On the whole it works brilliantly. I think it's a really excellent and thorough sample application.

Two small things I did notice:
1. For some reason, when I navigate to https://identityserver:7000/diagnostics I get a 404. Can't figure out why. Not super important, just odd.
2. There seems to be a bit of a race condition with the console app when running `docker compose up --build` for the first time, as it always fails with a 401 unauthorised. If you run it  again separately again later, it runs fine. Wondering if adding a heath check of some sorts to the docker compose file under IdentityServer would help?

**Comment by tnc1997** [comment]
Hi @GFoley83, thank you very much for your feedback and for testing out the sample. I've pushed up a couple of commits that should fix the issues that you mentioned.

**Comment by GFoley83** [comment]
That seems to have done the trick!
