### ISSUE TITLE
Trusting a self-signed certificate on Linux

### ISSUE THREAD

**Issue by tuana2k38** [tnc1997/samples#45]
**Describe the bug**

**Current behavior**
1. Step 1: Generate a self-signed certificate was successful
2. Step 2: Import the self-signed certificate. was not work!

**Expected behavior**

**Screenshots**
![image](https://github.com/tnc1997/samples/assets/61265047/6b7d6976-81fc-4232-96e3-49e4dca99167)

**Additional context**

**Comment by tnc1997** [comment]
Hi @tuana2k38, it looks like you are using Linux but that command is intended for use on Windows.

Please see [this](https://unix.stackexchange.com/a/132163) answer on Stack Exchange for details on trusting a self-signed certificate on Linux.

```shell
openssl req -x509 -newkey rsa:4096 -keyout localhost.key -out localhost.crt -subj "/CN=localhost" -addext "subjectAltName=DNS:localhost,DNS:api,DNS:identityserver"
sudo cp localhost.crt /usr/local/share/ca-certificates
sudo update-ca-certificates
```

**Comment by tuana2k38** [comment]
What about this cmd:
openssl pkcs12 -export -in localhost.crt -inkey localhost.key -out localhost.pfx -name "Adding JWT Bearer Authentication to a Hot Chocolate 12 GraphQL API".

**Comment by tnc1997** [comment]
> What about this cmd

Apologies for missing that, you will need that for the application.

**Comment by tuana2k38** [comment]
thanks for your support!
